// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen5_screen_init(void)
{
    ui_Screen5 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container5 = lv_obj_create(ui_Screen5);
    lv_obj_remove_style_all(ui_Container5);
    lv_obj_set_width(ui_Container5, 240);
    lv_obj_set_height(ui_Container5, 50);
    lv_obj_set_x(ui_Container5, 0);
    lv_obj_set_y(ui_Container5, -95);
    lv_obj_set_align(ui_Container5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container5, lv_color_hex(0x5CD1F7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_backbtn5 = lv_btn_create(ui_Container5);
    lv_obj_set_width(ui_backbtn5, 40);
    lv_obj_set_height(ui_backbtn5, 40);
    lv_obj_set_x(ui_backbtn5, -95);
    lv_obj_set_y(ui_backbtn5, 0);
    lv_obj_set_align(ui_backbtn5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_backbtn5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_backbtn5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label12 = lv_label_create(ui_backbtn5);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, -3);
    lv_obj_set_y(ui_Label12, -1);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "<");
    lv_obj_set_style_text_font(ui_Label12, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_nextbtn5 = lv_btn_create(ui_Container5);
    lv_obj_set_width(ui_nextbtn5, 40);
    lv_obj_set_height(ui_nextbtn5, 40);
    lv_obj_set_x(ui_nextbtn5, -50);
    lv_obj_set_y(ui_nextbtn5, 0);
    lv_obj_set_align(ui_nextbtn5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_nextbtn5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_nextbtn5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label13 = lv_label_create(ui_nextbtn5);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, ">");
    lv_obj_set_style_text_font(ui_Label13, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabView1 = lv_tabview_create(ui_Screen5, LV_DIR_TOP, 50);
    lv_obj_set_width(ui_TabView1, 240);
    lv_obj_set_height(ui_TabView1, 120);
    lv_obj_set_x(ui_TabView1, 0);
    lv_obj_set_y(ui_TabView1, -7);
    lv_obj_set_align(ui_TabView1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TabView1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags


    ui_Container6 = lv_obj_create(ui_Screen5);
    lv_obj_remove_style_all(ui_Container6);
    lv_obj_set_width(ui_Container6, 240);
    lv_obj_set_height(ui_Container6, 134);
    lv_obj_set_x(ui_Container6, 0);
    lv_obj_set_y(ui_Container6, 50);
    lv_obj_set_align(ui_Container6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_backbtn5, ui_event_backbtn5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_nextbtn5, ui_event_nextbtn5, LV_EVENT_ALL, NULL);

}
