// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen2_screen_init(void)
{
ui_Screen2 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Panel1 = lv_obj_create(ui_Screen2);
lv_obj_set_width( ui_Panel1, 269);
lv_obj_set_height( ui_Panel1, 44);
lv_obj_set_x( ui_Panel1, 0 );
lv_obj_set_y( ui_Panel1, -105 );
lv_obj_set_align( ui_Panel1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x84E5FA), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_manbtn = lv_btn_create(ui_Panel1);
lv_obj_set_width( ui_manbtn, 40);
lv_obj_set_height( ui_manbtn, 40);
lv_obj_set_x( ui_manbtn, -1 );
lv_obj_set_y( ui_manbtn, -9 );
lv_obj_add_flag( ui_manbtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_manbtn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label3 = lv_label_create(ui_manbtn);
lv_obj_set_width( ui_Label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label3,"<");

ui_scanbtn = lv_btn_create(ui_Panel1);
lv_obj_set_width( ui_scanbtn, 40);
lv_obj_set_height( ui_scanbtn, 40);
lv_obj_set_x( ui_scanbtn, 197 );
lv_obj_set_y( ui_scanbtn, -11 );
lv_obj_add_flag( ui_scanbtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_scanbtn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label4 = lv_label_create(ui_scanbtn);
lv_obj_set_width( ui_Label4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label4, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label4,"扫描");
lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label4, &ui_font_Font1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Switch2 = lv_switch_create(ui_Panel1);
lv_obj_set_width( ui_Switch2, 50);
lv_obj_set_height( ui_Switch2, 25);
lv_obj_set_x( ui_Switch2, 16 );
lv_obj_set_y( ui_Switch2, 3 );
lv_obj_set_align( ui_Switch2, LV_ALIGN_CENTER );


ui_testbtn = lv_btn_create(ui_Panel1);
lv_obj_set_width( ui_testbtn, 40);
lv_obj_set_height( ui_testbtn, 40);
lv_obj_set_x( ui_testbtn, 43 );
lv_obj_set_y( ui_testbtn, -9 );
lv_obj_add_flag( ui_testbtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_testbtn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label6 = lv_label_create(ui_testbtn);
lv_obj_set_width( ui_Label6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label6, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label6,">");

ui_wifiname = lv_roller_create(ui_Screen2);
lv_roller_set_options( ui_wifiname, "Option 1\nOption 2\nOption 3\nOption 4\nOption 5\nOption 6", LV_ROLLER_MODE_INFINITE );
lv_obj_set_width( ui_wifiname, 234);
lv_obj_set_height( ui_wifiname, 80);
lv_obj_set_x( ui_wifiname, -1 );
lv_obj_set_y( ui_wifiname, -41 );
lv_obj_set_align( ui_wifiname, LV_ALIGN_CENTER );

ui_Dropdown1 = lv_dropdown_create(ui_Screen2);
lv_dropdown_set_options( ui_Dropdown1, "12345678\n88888888\n00000000" );
lv_obj_set_width( ui_Dropdown1, 133);
lv_obj_set_height( ui_Dropdown1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Dropdown1, -49 );
lv_obj_set_y( ui_Dropdown1, 20 );
lv_obj_set_align( ui_Dropdown1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Dropdown1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags



ui_conbtn = lv_btn_create(ui_Screen2);
lv_obj_set_width( ui_conbtn, 40);
lv_obj_set_height( ui_conbtn, 40);
lv_obj_set_x( ui_conbtn, 176 );
lv_obj_set_y( ui_conbtn, 177 );
lv_obj_add_flag( ui_conbtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_conbtn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label7 = lv_label_create(ui_conbtn);
lv_obj_set_width( ui_Label7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label7, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label7,"连接");
lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label7, &ui_font_Font1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TextArea3 = lv_textarea_create(ui_Screen2);
lv_obj_set_width( ui_TextArea3, 162);
lv_obj_set_height( ui_TextArea3, 70);
lv_obj_set_x( ui_TextArea3, -34 );
lv_obj_set_y( ui_TextArea3, 76 );
lv_obj_set_align( ui_TextArea3, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_TextArea3,"Placeholder...");



lv_obj_add_event_cb(ui_manbtn, ui_event_manbtn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_scanbtn, ui_event_scanbtn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Switch2, ui_event_Switch2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_testbtn, ui_event_testbtn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_conbtn, ui_event_conbtn, LV_EVENT_ALL, NULL);

}
