// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"
#include "test_ui.h"

void ui_Screen4_screen_init(void)
{
    ui_Screen4 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container4 = lv_obj_create(ui_Screen4);
    lv_obj_remove_style_all(ui_Container4);
    lv_obj_set_width(ui_Container4, 240);
    lv_obj_set_height(ui_Container4, 50);
    lv_obj_set_x(ui_Container4, 0);
    lv_obj_set_y(ui_Container4, -95);
    lv_obj_set_align(ui_Container4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container4, lv_color_hex(0x5CD1F7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_backbtn4 = lv_btn_create(ui_Container4);
    lv_obj_set_width(ui_backbtn4, 40);
    lv_obj_set_height(ui_backbtn4, 40);
    lv_obj_set_x(ui_backbtn4, -95);
    lv_obj_set_y(ui_backbtn4, 0);
    lv_obj_set_align(ui_backbtn4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_backbtn4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_backbtn4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label10 = lv_label_create(ui_backbtn4);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, -3);
    lv_obj_set_y(ui_Label10, -1);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "<");
    lv_obj_set_style_text_font(ui_Label10, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_nextbtn4 = lv_btn_create(ui_Container4);
    lv_obj_set_width(ui_nextbtn4, 40);
    lv_obj_set_height(ui_nextbtn4, 40);
    lv_obj_set_x(ui_nextbtn4, -50);
    lv_obj_set_y(ui_nextbtn4, 0);
    lv_obj_set_align(ui_nextbtn4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_nextbtn4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_nextbtn4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label11 = lv_label_create(ui_nextbtn4);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, ">");
    lv_obj_set_style_text_font(ui_Label11, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_backbtn4, ui_event_backbtn4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_nextbtn4, ui_event_nextbtn4, LV_EVENT_ALL, NULL);

    test_picture(ui_Screen4);

}
