// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
#include "lv_port_indev.h"
#include "esp_log.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
void ui_event_wifibtn(lv_event_t * e);
lv_obj_t * ui_wifibtn;
lv_obj_t * ui_Label4;
lv_obj_t * ui_Roller1;
lv_obj_t * ui_date;
lv_obj_t * ui_time;
lv_obj_t * ui_Button1;
lv_obj_t * ui_Container3;
lv_obj_t * ui_Image3;
// CUSTOM VARIABLES


// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
lv_obj_t * ui_Screen2;
lv_obj_t * ui_Container1;
void ui_event_backbtn2(lv_event_t * e);
lv_obj_t * ui_backbtn2;
lv_obj_t * ui_Label1;
void ui_event_nextbtn2(lv_event_t * e);
lv_obj_t * ui_nextbtn2;
lv_obj_t * ui_Label2;
void ui_event_scanbtn(lv_event_t * e);
lv_obj_t * ui_scanbtn;
lv_obj_t * ui_Label3;
void ui_event_Switch1(lv_event_t * e);
lv_obj_t * ui_Switch1;
lv_obj_t * ui_wifiname;
lv_obj_t * ui_Dropdown1;
lv_obj_t * ui_Switch2;
void ui_event_conbtn(lv_event_t * e);
lv_obj_t * ui_conbtn;
lv_obj_t * ui_Label5;
lv_obj_t * ui_Label6;
// CUSTOM VARIABLES


// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
lv_obj_t * ui_Screen3;
lv_obj_t * ui_Container2;
void ui_event_backbtn3(lv_event_t * e);
lv_obj_t * ui_backbtn3;
lv_obj_t * ui_Label7;
void ui_event_nextbtn3(lv_event_t * e);
lv_obj_t * ui_nextbtn3;
lv_obj_t * ui_Label8;
lv_obj_t * ui_scanbtn2;
lv_obj_t * ui_Label9;
lv_obj_t * ui_Switch3;
void ui_event_TextArea3(lv_event_t * e);
lv_obj_t * ui_TextArea3;
lv_obj_t * ui_Keyboard1;
// CUSTOM VARIABLES


// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
lv_obj_t * ui_Screen4;
lv_obj_t * ui_Container4;
void ui_event_backbtn4(lv_event_t * e);
lv_obj_t * ui_backbtn4;
lv_obj_t * ui_Label10;
void ui_event_nextbtn4(lv_event_t * e);
lv_obj_t * ui_nextbtn4;
lv_obj_t * ui_Label11;
// CUSTOM VARIABLES


// SCREEN: ui_Screen5
void ui_Screen5_screen_init(void);
lv_obj_t * ui_Screen5;
lv_obj_t * ui_Container5;
void ui_event_backbtn5(lv_event_t * e);
lv_obj_t * ui_backbtn5;
lv_obj_t * ui_Label12;
void ui_event_nextbtn5(lv_event_t * e);
lv_obj_t * ui_nextbtn5;
lv_obj_t * ui_Label13;
lv_obj_t * ui_TabView1;
lv_obj_t * ui_Container6;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
const lv_img_dsc_t * ui_imgset_[1] = {&ui_img_333_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_wifibtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 30, 0, &ui_Screen2_screen_init);
    lv_indev_set_group(indev_keypad, group2);
    lv_group_focus_obj(ui_backbtn2);
    }
        if (event_code == LV_EVENT_FOCUSED) {
            ESP_LOGI("--","对象 %p 获得焦点\n", target);
            lv_obj_invalidate(lv_scr_act());  // 强制重绘屏幕
        } else if (event_code == LV_EVENT_DEFOCUSED) {
            ESP_LOGI("--","对象 %p 失去焦点\n", target);
        }
    // ESP_LOGI("ui_event_wifibtn","ui_event_wifibtn\n");
    // printf("ui_event_wifibtn\n");
}
void ui_event_backbtn2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 30, 0, &ui_Screen1_screen_init);
    lv_indev_set_group(indev_keypad, group1);
    lv_group_focus_obj(ui_wifibtn);
    }
}

void ui_event_nextbtn2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_FADE_ON, 30, 0, &ui_Screen3_screen_init);
    lv_indev_set_group(indev_keypad, group3);
    lv_group_focus_obj(ui_backbtn3);
    }
}

void ui_event_scanbtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        test_wifi_sacn(e);
    }
}

void ui_event_Switch1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        wifi_switch(e);
    }
}

void ui_event_conbtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        test_wifi_connect(e);
    }
}

void ui_event_backbtn3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 30, 0, &ui_Screen2_screen_init);
    lv_indev_set_group(indev_keypad, group2);
    lv_group_focus_obj(ui_backbtn2);
    }
}

void ui_event_nextbtn3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen4, LV_SCR_LOAD_ANIM_FADE_ON, 30, 0, &ui_Screen4_screen_init);
    lv_indev_set_group(indev_keypad, group4);
    lv_group_focus_obj(ui_backbtn4);
    }
}

void ui_event_TextArea3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard1,  ui_TextArea3);
    }
}

void ui_event_backbtn4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_FADE_ON, 30, 0, &ui_Screen3_screen_init);
    lv_indev_set_group(indev_keypad, group3);
    lv_group_focus_obj(ui_backbtn4);
    }
}

void ui_event_nextbtn4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen5, LV_SCR_LOAD_ANIM_FADE_ON, 30, 0, &ui_Screen5_screen_init);
        lv_indev_set_group(indev_keypad, group5);
        lv_group_focus_obj(ui_backbtn5);
    }
}

void ui_event_backbtn5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen4, LV_SCR_LOAD_ANIM_FADE_ON, 30, 0, &ui_Screen4_screen_init);
        lv_indev_set_group(indev_keypad, group4);
        lv_group_focus_obj(ui_backbtn4);
    }
}

void ui_event_nextbtn5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 30, 0, &ui_Screen1_screen_init);
    lv_indev_set_group(indev_keypad, group1);
    lv_group_focus_obj(ui_wifibtn);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui_Screen2_screen_init();
    ui_Screen3_screen_init();
    ui_Screen4_screen_init();
    ui_Screen5_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
