// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "../lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Image3;
void ui_event_wifibtn( lv_event_t * e);
extern lv_obj_t *ui_wifibtn;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_Roller1;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t *ui_Screen2;
extern lv_obj_t *ui_Panel1;
void ui_event_manbtn( lv_event_t * e);
extern lv_obj_t *ui_manbtn;
extern lv_obj_t *ui_Label3;
void ui_event_scanbtn( lv_event_t * e);
extern lv_obj_t *ui_scanbtn;
extern lv_obj_t *ui_Label4;
void ui_event_wifiswitch( lv_event_t * e);
extern lv_obj_t *ui_wifiswitch;
void ui_event_testbtn( lv_event_t * e);
extern lv_obj_t *ui_testbtn;
extern lv_obj_t *ui_Label6;
extern lv_obj_t *ui_wifiname;
extern lv_obj_t *ui_Dropdown1;
void ui_event_conbtn( lv_event_t * e);
extern lv_obj_t *ui_conbtn;
extern lv_obj_t *ui_Label7;
extern lv_obj_t *ui_TextArea3;
// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
extern lv_obj_t *ui_Screen3;
extern lv_obj_t *ui_Panel2;
void ui_event_wifibtn32( lv_event_t * e);
extern lv_obj_t *ui_wifibtn32;
extern lv_obj_t *ui_Label2;
extern lv_obj_t *ui_Button5;
extern lv_obj_t *ui_Label5;
extern lv_obj_t *ui_Switch1;
extern lv_obj_t *ui_TextArea1;
extern lv_obj_t *ui_Keyboard2;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_333_png);   // assets\333.png

LV_FONT_DECLARE( ui_font_Font1);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
