// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "../lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
void ui_event_wifibtn(lv_event_t * e);
extern lv_obj_t * ui_wifibtn;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Roller1;
extern lv_obj_t * ui_date;
extern lv_obj_t * ui_time;
extern lv_obj_t * ui_Button1;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Container1;
void ui_event_backbtn2(lv_event_t * e);
extern lv_obj_t * ui_backbtn2;
extern lv_obj_t * ui_Label1;
void ui_event_nextbtn2(lv_event_t * e);
extern lv_obj_t * ui_nextbtn2;
extern lv_obj_t * ui_Label2;
void ui_event_scanbtn(lv_event_t * e);
extern lv_obj_t * ui_scanbtn;
extern lv_obj_t * ui_Label3;
void ui_event_Switch1(lv_event_t * e);
extern lv_obj_t * ui_Switch1;
extern lv_obj_t * ui_wifiname;
extern lv_obj_t * ui_Dropdown1;
extern lv_obj_t * ui_Switch2;
void ui_event_conbtn(lv_event_t * e);
extern lv_obj_t * ui_conbtn;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label6;
// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_Container2;
void ui_event_backbtn3(lv_event_t * e);
extern lv_obj_t * ui_backbtn3;
extern lv_obj_t * ui_Label7;
void ui_event_nextbtn3(lv_event_t * e);
extern lv_obj_t * ui_nextbtn3;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_scanbtn2;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Switch3;
void ui_event_TextArea3(lv_event_t * e);
extern lv_obj_t * ui_TextArea3;
extern lv_obj_t * ui_Keyboard1;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_333_png);    // assets\333.png

LV_FONT_DECLARE(ui_font_songtibpp4);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
