// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "../lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
void ui_event_wifibtn(lv_event_t * e);
extern lv_obj_t * ui_wifibtn;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Roller1;
extern lv_obj_t * ui_date;
extern lv_obj_t * ui_time;
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_Image3;
// CUSTOM VARIABLES

// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Container1;
void ui_event_backbtn2(lv_event_t * e);
extern lv_obj_t * ui_backbtn2;
extern lv_obj_t * ui_Label1;
void ui_event_nextbtn2(lv_event_t * e);
extern lv_obj_t * ui_nextbtn2;
extern lv_obj_t * ui_Label2;
void ui_event_scanbtn(lv_event_t * e);
extern lv_obj_t * ui_scanbtn;
extern lv_obj_t * ui_Label3;
void ui_event_Switch1(lv_event_t * e);
extern lv_obj_t * ui_Switch1;
extern lv_obj_t * ui_wifiname;
extern lv_obj_t * ui_Dropdown1;
extern lv_obj_t * ui_Switch2;
void ui_event_conbtn(lv_event_t * e);
extern lv_obj_t * ui_conbtn;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label6;
// CUSTOM VARIABLES

// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_Container2;
void ui_event_backbtn3(lv_event_t * e);
extern lv_obj_t * ui_backbtn3;
extern lv_obj_t * ui_Label7;
void ui_event_nextbtn3(lv_event_t * e);
extern lv_obj_t * ui_nextbtn3;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_scanbtn2;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Switch3;
void ui_event_TextArea3(lv_event_t * e);
extern lv_obj_t * ui_TextArea3;
extern lv_obj_t * ui_Keyboard1;
// CUSTOM VARIABLES

// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
extern lv_obj_t * ui_Screen4;
extern lv_obj_t * ui_Container4;
void ui_event_backbtn4(lv_event_t * e);
extern lv_obj_t * ui_backbtn4;
extern lv_obj_t * ui_Label10;
void ui_event_nextbtn4(lv_event_t * e);
extern lv_obj_t * ui_nextbtn4;
extern lv_obj_t * ui_Label11;
// CUSTOM VARIABLES

// SCREEN: ui_Screen5
void ui_Screen5_screen_init(void);
extern lv_obj_t * ui_Screen5;
extern lv_obj_t * ui_Container5;
void ui_event_backbtn5(lv_event_t * e);
extern lv_obj_t * ui_backbtn5;
extern lv_obj_t * ui_Label12;
void ui_event_nextbtn5(lv_event_t * e);
extern lv_obj_t * ui_nextbtn5;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_TabView1;
extern lv_obj_t * ui_Container6;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_333_png);    // assets/333.png

// FONTS
LV_FONT_DECLARE(ui_font_songtibpp4);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
